name: auth_2fa
description: Demonstrates how 2FA works with df-django-auth
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  djangoflow_auth: ^0.2.2+1
  djangoflow_openapi: ^0.0.22
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  flutter_list_bloc: ^4.1.0
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^9.1.1
  json_annotation: ^4.8.1
  list_bloc: ^3.1.0
  openapi_repository_annotations: ^1.2.3
  path_provider: ^2.0.11
  progress_builder: ^1.1.3
  reactive_forms: ^16.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  icons_launcher: ^2.1.3
  openapi_repository: ^3.3.0
  
dependency_overrides:
  # use local dependency for djangoflow_openapi to override the one from pub.dev
  djangoflow_openapi:
    path: ./packages/djangoflow_openapi
  oauth2_client:
    git:
      url: https://github.com/jheld/oauth2_client.git
      ref: master

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo/
