name: simple_auth

packages:
  - packages/auth
  - packages/djangoflow_openapi

command:
  bootstrap:
    hooks:
      post: melos generate

scripts:
  generate:
    description: Generate all files
    run: melos run generate-flutter --no-select && melos run generate-dart --no-select

  generate-flutter:
    description: Generate flutter files
    run: flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dependsOn: build_runner

  generate-dart:
    description: Generate dart files
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
    packageFilters:
      flutter: false
      dart: true
      dependsOn: build_runner
