name: simple_auth
description: Simple Auth demonstrates how to use the djangoflow_auth package along with additional social authentication packages.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  djangoflow_auth: ^0.2.1+5
  djangoflow_auth_apple: ^0.0.5+7
  djangoflow_auth_discord: ^0.0.4+8
  djangoflow_auth_facebook: ^0.0.4+7
  djangoflow_auth_google: ^0.0.3+7
  djangoflow_openapi: ^0.0.18
  flutter_bloc: ^8.1.3
  firebase_core: ^2.14.0
  flutter_facebook_auth: ^6.0.0
  google_sign_in: ^6.1.4
  hydrated_bloc: ^9.1.1
  openapi_repository_annotations: ^1.1.0
  path_provider: ^2.0.11
  progress_builder: ^1.1.3
  reactive_forms: ^16.0.4
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  icons_launcher: ^2.1.3
  openapi_repository: ^3.0.0

dependency_overrides:
  # use local dependency for djangoflow_openapi to override the one from pub.dev
  djangoflow_openapi:
    path: ./packages/djangoflow_openapi
  oauth2_client:
    git:
      url: https://github.com/jheld/oauth2_client.git
      ref: master

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo/
