name: djangoflow_openapi
version: 1.0.0
description: OpenAPI API client
homepage: homepage

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  copy_with_extension: ^5.0.4
  dio: '^5.2.0'
  json_annotation: '^4.4.0'

dev_dependencies:
  build_runner: any
  copy_with_extension_gen: ^5.0.4
  json_serializable: '^6.1.5'
  test: ^1.16.0
